import Head from "next/head";
import { Inter, Montserrat } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import FontSelect from "@/components/FontSelect";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ weight: "600", subsets: ["latin"] });

const fonts = ["Inter", "Montserrat"];

export default function Home() {
  const [selectedFont, setSelectedFont] = React.useState("Inter");

  const handleSelect = React.useCallback(
    (e: { target: { value: React.SetStateAction<string> } }) => {
      setSelectedFont(e.target.value);
    },
    []
  );

  return (
    <>
      <Head>
        <title>Ledbim Font Checker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>Ledbim Font Checker</h1>
        <FontSelect
          fonts={fonts}
          onChange={(e: { target: { value: React.SetStateAction<string> } }) =>
            handleSelect(e)
          }
        />
        <div className={styles.container}>
          <div className={styles.font_wrapper}>
            <h2 className={montserrat.className}>Ledbim {selectedFont} 600</h2>
            <h3 className={montserrat.className}>Ledbim {selectedFont} 600</h3>
            <h4 className={montserrat.className}>Ledbim {selectedFont} 600</h4>
            <h5 className={montserrat.className}>Ledbim {selectedFont} 600</h5>
          </div>
        </div>
      </main>
    </>
  );
}
