import Head from "next/head";
import { Inter, Montserrat, Asar } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import FontSelect from "@/components/FontSelect";
import React from "react";
import TextInput from "@/components/TextInput";

const inter = Inter({ weight: "600", subsets: ["latin"] });
const montserrat = Montserrat({ weight: "600", subsets: ["latin"] });
const asar = Asar({ weight: "400", subsets: ["latin"] });
const fonts = ["Inter", "Montserrat", "Asar"];

export default function Home() {
  const [selectedFont, setSelectedFont] = React.useState("Inter");
  const [font, setFont] = React.useState(inter);
  const [text, setText] = React.useState(
    `Ledbim ${selectedFont} ${font.style.fontWeight}`
  );
  React.useEffect(() => {
    if (selectedFont === "Inter") {
      setFont(inter);
    } else if (selectedFont === "Montserrat") {
      setFont(montserrat);
    } else if (selectedFont === "Asar") {
      setFont(asar);
    }
  }, [selectedFont]);

  const handleSelect = React.useCallback(
    (e: { target: { value: React.SetStateAction<string> } }) => {
      setSelectedFont(e.target.value);
    },
    []
  );

  return (
    <>
      <Head>
        <title>Ledbim Font Checker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>Ledbim Font Checker</h1>
        <div className={styles.input_container}>
          <FontSelect fonts={fonts} onChange={(e: any) => handleSelect(e)} />
          <TextInput
            onChange={(e: {
              target: { value: React.SetStateAction<string> };
            }) => setText(e.target.value)}
          />
        </div>
        <div className={styles.container}>
          <div className={styles.font_wrapper}>
            <h2 className={font.className}>{text}</h2>
            <h3 className={font.className}>{text}</h3>
            <h4 className={font.className}>{text}</h4>
            <h5 className={font.className}>{text}</h5>
            <h6 className={font.className}>{text}</h6>
          </div>
        </div>
      </main>
    </>
  );
}
